### ISSUE TITLE
object getters are not seen by the compiler

### ISSUE THREAD

**Issue by ConneXNL** [schmittjoh/twig.js#85]
When i have an object with a getter, Twig Js cannot see it causing the value to be undefined.

**Comment by hnrysmth** [comment]
Wow this issue is so many years old now. I can't believe I just let it trail off like that, but hey, I guess that's how it goes sometimes. I know you almost definitely won't be interested in this issue any more, so I'll close it, but if you do decide you wanna pick it back up then be my guest! :smile:

What would be awesome is, if you do wanna get this fixed, could you maybe write the example yourself? I remember I kept trying and trying to guess what the bug looked like and never really figuring it out. Probably easier if you write the test case come to think of it.

Anyway I hope you've had an awesome few years since you last heard from me :joy:
